networks:
  raspi-docker_default:
    external: true
    name: "raspi-docker_default"


services:
  brandstof-berkenaar:
    command:
      - "pdm"
      - "run"
      - "streamlit"
      - "run"
      - "dashboard.py"
    container_name: "brandstof-berkenaar"
    image: "brandstof-berekenaar:latest" # TODO: This is a build
    ipc: "private"
    network_mode: "bridge"
    ports:
      - "8501:8501/tcp"
    restart: "unless-stopped"

  duplicati:
    container_name: "duplicati"
    environment:
      - "TZ=Europe/Amsterdam"
      - "PUID=1000"
      - "PGID=1000"
      - "SETTINGS_ENCRYPTION_KEY=DUPLICATI_ENCRYPTION_KEY"
      - "DUPLICATI__WEBSERVICE_PASSWORD=DUPLICATI_ADMIN_PASSWORD"
    image: "linuxserver/duplicati:latest"
    network_mode: "bridge"
    ports:
      - "8200:8200/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/abel/docker-volumes/duplicati/config:/config"
      - "/home/abel/docker-volumes:/source"
      - "/mnt/NAS/Backups/duplicati:/backups"

  esphome:
    container_name: "esphome"
    command:
      - "dashboard"
      - "/config"
    entrypoint:
      - "/entrypoint.sh"
    image: "esphome/esphome:latest"
    network_mode: "bridge"
    ports:
      - "6052:6052/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/abel/docker-volumes/esphome:/config"
    environment:
      USERNAME: "${ESPHOME_USERNAME}"
      PASSWORD: "${ESPHOME_PASSWORD}"

  homeassistant:
    container_name: "homeassistant"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - "TZ=Europe/Amsterdam"
    hostname: "pietje-1"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: "host"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    volumes:
      - "/dev:/dev"
      - "/home/abel/docker-volumes/homeassistant:/config"
      - "/run/dbus:/run/dbus:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  influxdb:
    container_name: "influxdb"
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_BUCKET=ha_insights"
    env_file:
      - /home/abel/raspi-docker/.env
    image: "influxdb:latest"
    networks:
      - "raspi-docker_default"
    ports:
      - "8086:8086/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/abel/docker-volumes/influxdb/config:/etc/influxdb2"
      - "/home/abel/docker-volumes/influxdb/data:/var/lib/influxdb2"

  matter-server:
    container_name: "matter-server"
    expose:
      - "5580/tcp"
    hostname: "pietje-1"
    image: "ghcr.io/matter-js/python-matter-server:stable"
    network_mode: "host"
    restart: "unless-stopped"
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - "/home/abel/docker-volumes/matter-server:/data"

  mosquitto:
    container_name: "mosquitto"
    image: "eclipse-mosquitto:latest"
    network_mode: "bridge"
    ports:
      - "1883:1883/tcp"
      - "9001:9001/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/abel/docker-volumes/mosquitto/config:/mosquitto/config"
      - "/home/abel/docker-volumes/mosquitto/data:/mosquitto/data"
      - "/home/abel/docker-volumes/mosquitto/log:/mosquitto/log"

    working_dir: "/"

  zigbee2mqtt:
    container_name: "zigbee2mqtt"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - "TZ=Europe/Amsterdam"
    image: "koenkk/zigbee2mqtt:latest"
    network_mode: "bridge"
    ports:
      - "8080:8080/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/abel/docker-volumes/zigbee2mqtt/data:/app/data"
      - "/run/udev:/run/udev:ro"

version: "3.6"
