version: "3.6"
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    hostname: raspberrypi
    network_mode: host
    expose:
      - 8581/tcp
    restart: always
    volumes:
      - ./docker-volumes/homebridge:/homebridge

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ipc: private
    logging:
      driver: json-file
      options: {}
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1001
      - PGID=1023
      - TZ=Etc/UTC
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 50M
    restart: unless-stopped
    volumes:
      - /mnt/NAS/:/data
      - ./docker-volumes/sonarr/:/config
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ipc: private
    logging:
      driver: json-file
      options: {}
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - PUID=1002
      - PGID=1023
      - TZ=Etc/UTC
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 50M
    restart: unless-stopped
    volumes:
      - /mnt/NAS/:/data
      - ./docker-volumes/radarr/:/config

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1004
      - PGID=1023
      - TZ=Etc/UTC
    volumes:
      - ./docker-volumes/bazarr:/config
      - /mnt/NAS/Movies:/movies
      - /mnt/NAS/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  readarr:
    image: linuxserver/readarr:0.3.6-nightly
    container_name: readarr
    environment:
      - PUID=1005
      - PGID=1023
      - TZ=Etc/UTC
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 50M
    volumes:
      - ./docker-volumes/readarr:/config
      - /mnt/NAS/Books:/books
      - /mnt/NAS/Downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1006
      - PGID=1023
      - TZ=Etc/UTC
    volumes:
      - ./docker-volumes/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscaled
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: ./.tailscale.env
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/lib:/var/lib
