# Stack for trying out new services before giving them a permanent home
services:
#  ha-ipaper:
#    container_name: ha-ipaper
#    environment:
#      - "HA_IPAPER_GENERAL__homeassistant_url=http://127.0.0.1:423"
#      - "HA_IPAPER_GENERAL__homeassistant_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0N2UxMGVlNDhjM2M0ZDI5YWJkYmUzN2U5MzA3MTQyMSIsImlhdCI6MTc3ODYxNzUzMCwiZXhwIjoyMDkzOTc3NTMwfQ.XPEhMOg73zfWVua5DI4kzLBE5CW_74r33UmwZgu1sug"
#    build:
#      context: "/home/docker/ha-ipaper/"
#      dockerfile: "docker/Dockerfile"
#    network_mode: "host"



